import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.scss";
import Header from "@/components/header/header";

const interTight = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gatekeep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interTight.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
